version: '3.3'
services:
  jenkins:
    build: ./jenkins
    privileged: true
    user: root
    restart: on-failure
    ports:
      - "8080:8080"
    container_name: jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
